# LightGBM 回归 — 完整流程 Demo

本 notebook 演示使用 `ml_tool` 工具包完成 LightGBM 回归任务的完整流程：

1. 数据初始化与集合划分（train / test / OOT）
2. 特征分析（缺失率、一值率、分位数统计、PSI、相关性）
3. 特征筛选（回归模式：缺失率 + PSI + 相关性，跳过 IV/WOE）
4. 模型训练（Hyperopt 自动调参）
5. 自定义超参数搜索空间
6. 回归评估报告（MAE / RMSE / R² / 分桶分析）
7. 特征分析报告
8. 模型保存与加载验证

In [1]:
import pandas as pd
import numpy as np
from ml_tool import FeatureAnalyzer, FeatureSelector, ModelTrainer, ReportGenerator, split_dataset

np.random.seed(42)
n = 3000
dates = pd.date_range('2024-01-01', periods=n, freq='D').to_series().sample(frac=1, random_state=42).values

f1 = np.random.randn(n)
f2 = np.random.rand(n)
f3 = np.random.randn(n) * 2
f4 = np.random.rand(n)
f5 = np.random.randn(n)
noise = np.random.randn(n) * 0.5
y_reg = 2 * f1 - f2 + noise

df_raw = pd.DataFrame({
    'f1': f1, 'f2': f2, 'f3': f3, 'f4': f4, 'f5': f5,
    'y_reg': y_reg,
    'report_date': dates,
})
df_raw.loc[df_raw.sample(frac=0.05, random_state=0).index, 'f2'] = np.nan

df = split_dataset(df_raw, date_col='report_date', oot_date='2031-01-01', train_ratio=0.8)
df['month'] = df['report_date'].dt.to_period('M').astype(str)
print(df.shape, df['dataset'].value_counts().sort_index().to_dict())
print('目标变量统计:')
print(df['y_reg'].describe())

OUTPUT_DIR = './output/lgbm_reg'
# 模拟附加列（在 split_dataset 之后追加）
df['score_A']    = np.random.uniform(300, 700, len(df))   # 模拟标品A分
df['score_B']    = np.random.uniform(350, 750, len(df))   # 模拟标品B分
df['gain_score'] = np.random.uniform(0, 1, len(df))       # 模拟外部增益分
df['overdue_30'] = np.random.binomial(1, 0.12, len(df))   # 模拟逾期30天标签
df['overdue_60'] = np.random.binomial(1, 0.08, len(df))   # 模拟逾期60天标签

数据集划分完成（切点: 2031-01-01, train_ratio=0.8）
  train:   2045  (68.2%)
  test :    512  (17.1%)
  oot  :    443  (14.8%)
(3000, 9) {'oot': 443, 'test': 512, 'train': 2045}
目标变量统计:
count    3000.000000
mean       -0.423159
std         2.053584
min        -8.160994
25%        -1.822947
50%        -0.428424
75%         0.920636
max         7.635985
Name: y_reg, dtype: float64

## 1. 特征分析

In [2]:
feature_cols = ['f1', 'f2', 'f3', 'f4', 'f5']
analyzer = FeatureAnalyzer(df[feature_cols])

print('=== 缺失率 ==='); display(analyzer.missing_rate())
print('=== 一值率 ==='); display(analyzer.single_value_rate())
print('=== 分位数统计 ==='); display(analyzer.quantile_stats())

base_df    = df[df['dataset'] == 'train'][feature_cols].copy()
compare_df = df[df['dataset'] == 'oot'][feature_cols].copy()
psi_df = analyzer.psi(base_df, compare_df)
print('=== PSI（train vs OOT）==='); display(psi_df)
print('=== 特征间相关性（|r|>0.3）==='); display(analyzer.correlation(threshold=0.3))
# 回归任务无 IV 计算

=== 缺失率 ===

  特征名  缺失数   缺失率
0  f1    0  0.00
1  f2  150  0.05
2  f3    0  0.00
3  f4    0  0.00
4  f5    0  0.00

=== 一值率 ===

  特征名      最高频值     一值率
0  f1  0.496714  0.0003
1  f2       NaN  0.0500
2  f3 -0.380482  0.0003
3  f4  0.648747  0.0003
4  f5  1.508311  0.0003

=== 分位数统计 ===

,特征名,样本数,均值,标准差,最小值,1%分位,5%分位,25%分位,中位数,75%分位,95%分位,99%分位,最大值
0,f1,3000.0,0.032001,0.986808,-3.241267,-2.219490,-1.565074,-0.627541,0.024365,0.673591,1.673504,2.364268,3.926238
1,f2,2850.0,0.496442,0.287895,0.000031,0.011646,0.052793,0.248603,0.492746,0.743174,0.951271,0.989204,0.999461
2,f3,3000.0,-0.035827,2.080612,-7.673311,-4.769815,-3.475749,-1.440090,-0.065302,1.397700,3.363288,4.994851,7.058110
3,f4,3000.0,0.499154,0.291073,0.000158,0.008810,0.050133,0.244087,0.490364,0.756368,0.952307,0.990111,0.999673
4,f5,3000.0,0.012466,0.997329,-3.375579,-2.342613,-1.606774,-0.651083,0.015079,0.673944,1.612335,2.384736,3.428910

=== PSI（train vs OOT）===

  特征名     PSI
0  f1  0.0187
1  f2  0.0283
2  f3  0.0242
3  f4  0.0064
4  f5  0.0235

=== 特征间相关性（|r|>0.3）===

Empty DataFrame
Columns: [特征A, 特征B, 相关系数]
Index: []

## 2. 特征筛选（回归：缺失率 + PSI + 相关性，不做 IV 筛选）

In [3]:
import os

reporter = ReportGenerator(output_dir=OUTPUT_DIR)
train_df = df[df['dataset'] == 'train'].reset_index(drop=True)

# 回归任务：psi_filter=False 关闭自动 PSI 过滤，corr_filter=False 关闭自动相关性过滤
# iv_threshold=0.0 跳过 IV 筛选
selector = FeatureSelector(
    iv_threshold=0.0,
    psi_threshold=0.5,
    missing_threshold=0.98,
    corr_threshold=0.97,
    psi_filter=False,
    corr_filter=False,
)
selector.fit(
    df=train_df[feature_cols + ['y_reg']],
    target='y_reg',
    base_df=base_df,
    compare_df=compare_df,
)
print('入选特征:', selector.get_selected())
print('剔除特征:', selector.dropped_cols)
display(selector.get_report())

analysis = {
    '缺失率': analyzer.missing_rate(),
    '分位数统计': analyzer.quantile_stats(),
    'PSI': psi_df,
    '相关性': analyzer.correlation(threshold=0.0),
}
path = reporter.feature_selection_report(selector.get_report(), analysis_results=analysis)
print('特征筛选报告:', path)

入选特征:

 ['f1', 'f2', 'f3', 'f4', 'f5']
剔除特征: []

C:\miniconda\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\miniconda\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\miniconda\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\miniconda\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\miniconda\lib\site-packages\pandas\core\arraylike.py:396: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

  特征名     缺失率     PSI   IV 是否保留 剔除原因
0  f1  0.0000  0.0187  inf   保留
1  f2  0.0494  0.0283  inf   保留
2  f3  0.0000  0.0242  inf   保留
3  f4  0.0000  0.0064  inf   保留
4  f5  0.0000  0.0235  inf   保留

特征筛选报告: ./output/lgbm_reg\02_feature_selection\特征筛选报告.xlsx

## 3. 模型训练（LightGBM 回归）

In [4]:
selected = selector.get_selected()

X_train = df[df['dataset'] == 'train'][selected].reset_index(drop=True)
y_train = df[df['dataset'] == 'train']['y_reg'].reset_index(drop=True)
X_test  = df[df['dataset'] == 'test'][selected].reset_index(drop=True)
y_test  = df[df['dataset'] == 'test']['y_reg'].reset_index(drop=True)
X_oot   = df[df['dataset'] == 'oot'][selected].reset_index(drop=True)
y_oot   = df[df['dataset'] == 'oot']['y_reg'].reset_index(drop=True)

# n_trials 实际建议 100，这里用 20 演示
trainer = ModelTrainer(model_type='lgbm_reg', n_trials=20)
trainer.fit(
    X_train, y_train,
    X_test,  y_test,
    X_oot,   y_oot,
    save_dir=OUTPUT_DIR,
)
print('入模特征数:', len(trainer.selected_features))
print('入模特征:', trainer.selected_features)
print('最优参数:', trainer.best_params)

LGBM回归 第1轮（固定参数训练）

LGBM回归 第2轮（超参搜索）:   0%|                                  | 0/20 [00:00<?, ?it/s]

调参日志已保存至: ./output/lgbm_reg\03_model_tuning\tuning_log.xlsx
模型已保存至: ./output/lgbm_reg\05_model_deploy
入模特征数: 5
入模特征: ['f1', 'f2', 'f3', 'f4', 'f5']
最优参数: {'bagging_fraction': 0.7000000000000001, 'feature_fraction': 1.0, 'lambda_l1': 13, 'lambda_l2': 13, 'learning_rate': 0.037170468322258544, 'max_depth': 6, 'min_data_in_leaf': 20, 'num_leaves': 104, 'boosting_type': 'gbdt', 'objective': 'regression', 'metric': 'mae', 'num_threads': -1, 'verbose': -1, 'bagging_freq': 2, 'n_estimators': 550}

In [5]:
print('调参日志（前 10 行，按轮次/试验顺序）:')
display(
    trainer.trials_log[['round', 'trial', 'loss', 'is_best', 'train_mae', 'test_mae', 'oot_mae']]
    .head(10)
)

调参日志（前 10 行，按轮次/试验顺序）:

  round  trial      loss  is_best  train_mae  test_mae  oot_mae
0   第1轮      1  1.020964    False     0.3623    0.4221   0.4274
1   第2轮      1  0.975789    False     0.3824    0.4179   0.4217
2   第2轮      2  1.058793    False     0.3474    0.4126   0.4291
3   第2轮      3  1.030612    False     0.3544    0.4218   0.4262
4   第2轮      4  1.014230    False     0.3676    0.4199   0.4275
5   第2轮      5  0.985613    False     0.3779    0.4211   0.4235
6   第2轮      6  0.985027    False     0.3776    0.4149   0.4217
7   第2轮      7  1.058093    False     0.3540    0.4276   0.4361
8   第2轮      8  0.960224    False     0.4099    0.4211   0.4298
9   第2轮      9  0.958020    False     0.4038    0.4193   0.4259

## 4. 自定义超参数空间（可选）

In [6]:
# 查看默认固定参数
default_params = trainer.get_default_params(n_data=len(X_train))
print('默认固定参数:')
for k, val in default_params.items():
    print(f'  {k:25s}: {val}')

print()
# 查看默认搜索空间（返回普通 dict，可直接覆盖任意 key）
default_space = trainer.get_default_space(n_data=len(X_train))
print('默认搜索空间 key:')
for k, val in default_space.items():
    print(f'  {k:25s}: {val}')

默认固定参数:
  boosting_type            : gbdt
  objective                : regression
  metric                   : mae
  num_threads              : -1
  verbose                  : -1
  bagging_freq             : 2
  num_leaves               : 64
  max_depth                : 6
  n_estimators             : 800
  learning_rate            : 0.05
  bagging_fraction         : 0.8
  feature_fraction         : 0.8
  lambda_l1                : 5
  lambda_l2                : 5
  min_data_in_leaf         : 20

默认搜索空间 key:
  boosting_type            : gbdt
  objective                : regression
  metric                   : mae
  num_threads              : -1
  verbose                  : -1
  bagging_freq             : 2
  bagging_fraction         : 0 float
1   hyperopt_param
2     Literal{bagging_fraction}
3     quniform
4       Literal{0.6}
5       Literal{1.0}
6       Literal{0.1}
  feature_fraction         : 0 float
1   hyperopt_param
2     Literal{feature_fraction}
3     quniform
4       Literal{0.6}
5       Literal{1.0}
6       Literal{0.1}
  max_depth                : 0 float
1   hyperopt_param
2     Literal{max_depth}
3     quniform
4       Literal{4}
5       Literal{8}
6       Literal{1}
  num_leaves               : 0 float
1   hyperopt_param
2     Literal{num_leaves}
3     quniform
4       Literal{16}
5       Literal{128}
6       Literal{8}
  n_estimators             : 0 float
1   hyperopt_param
2     Literal{n_estimators}
3     quniform
4       Literal{500}
5       Literal{1000}
6       Literal{50}
  learning_rate            : 0 float
1   hyperopt_param
2     Literal{learning_rate}
3     uniform
4       Literal{0.005}
5       Literal{0.05}
  lambda_l1                : 0 hyperopt_param
1   Literal{lambda_l1}
2   randint
3     Literal{0}
4     Literal{20}
  lambda_l2                : 0 hyperopt_param
1   Literal{lambda_l2}
2   randint
3     Literal{0}
4     Literal{20}
  min_data_in_leaf         : 0 float
1   hyperopt_param
2     Literal{min_data_in_leaf}
3     quniform
4       Literal{10}
5       Literal{40}
6       Literal{10}

In [7]:
from hyperopt import hp

# 基于默认空间修改部分参数，限制树深度和学习率
custom_space = trainer.get_default_space(n_data=len(X_train))
custom_space['learning_rate']    = hp.uniform('learning_rate', 0.005, 0.02)
custom_space['max_depth']        = hp.quniform('max_depth', 2, 4, 1)
custom_space['num_leaves']       = hp.quniform('num_leaves', 4, 24, 4)
custom_space['n_estimators']     = hp.quniform('n_estimators', 100, 400, 50)
custom_space['bagging_fraction'] = 0.8   # 固定为常量，不参与搜索

# 自定义固定参数（可选，不传则使用默认）
custom_p1 = trainer.get_default_params(n_data=len(X_train))

trainer_custom = ModelTrainer(model_type='lgbm_reg', n_trials=10)
trainer_custom.fit(
    X_train, y_train, X_test, y_test, X_oot, y_oot,
    custom_params=custom_p1,
    custom_space=custom_space,
)
print('最终参数:')
for k, val in trainer_custom.best_params.items():
    print(f'  {k:25s}: {val}')

LGBM回归 第1轮（固定参数训练）

LGBM回归 第2轮（超参搜索）:   0%|                                  | 0/10 [00:00<?, ?it/s]

最终参数:
  feature_fraction         : 1.0
  lambda_l1                : 11
  lambda_l2                : 19
  learning_rate            : 0.01577641448628668
  max_depth                : 3
  min_data_in_leaf         : 20
  num_leaves               : 12
  boosting_type            : gbdt
  objective                : regression
  metric                   : mae
  num_threads              : -1
  verbose                  : -1
  bagging_freq             : 2
  n_estimators             : 350

## 5. 模型评估报告

In [8]:
# 特征重要性
fi_df = pd.DataFrame({
    'feature':    trainer._trainer.model.feature_name(),
    'importance': trainer._trainer.model.feature_importance('gain'),
})

month_data = {
    '训练集': df[df['dataset'] == 'train'][['month']].reset_index(drop=True),
    '验证集': df[df['dataset'] == 'test'][['month']].reset_index(drop=True),
    'OOT':   df[df['dataset'] == 'oot'][['month']].reset_index(drop=True),
}
datasets_reg = {
    '训练集': (y_train.values, trainer.predict(X_train)),
    '验证集': (y_test.values,  trainer.predict(X_test)),
    'OOT':   (y_oot.values,   trainer.predict(X_oot)),
}

import numpy as np
label_col_data = {
    '训练集': (y_train.values > 0).astype(int),
    '验证集': (y_test.values  > 0).astype(int),
    'OOT':   (y_oot.values   > 0).astype(int),
}

reg_result = reporter.regression_report(
    datasets_reg,
    filename='LightGBM_回归模型评估报告',
    n_bins=10,
    month_col_data=month_data,
    label_col_data=label_col_data,
    feature_importance=fi_df,
    raw_df=df,
    target_col='y_reg',
    gain_score_col='gain_score', gain_label_col='overdue_30',
    scorecard_cols=['score_A', 'score_B'],
    scorecard_label_cols=['overdue_30', 'overdue_60'],
)
display(reg_result['summary'])
print('Excel:', reg_result['excel_path'])
print('HTML: ', reg_result['html_path'])

,数据集,RMSE,MAE,R2,MAPE(%),Pearson相关系数,Pearson_p值,Spearman相关系数,Spearman_p值,样本量
0,训练集,0.5037,0.3937,0.9394,105.6396,0.9694,0.0,0.9691,0.0,2045
1,验证集,0.5385,0.4197,0.9331,103.5968,0.9662,0.0,0.9648,0.0,512
2,OOT,0.5549,0.4213,0.9258,90.2853,0.9627,0.0,0.9603,0.0,443

Excel: ./output/lgbm_reg\04_model_report\LightGBM_回归模型评估报告.xlsx
HTML:  ./output/lgbm_reg\04_model_report\LightGBM_回归模型评估报告.html

In [9]:
print('=== 真实值分桶（三集合，训练集切点）===')
display(reg_result['sheets']['真实值分桶'])

print('=== 预测值分桶（三集合，训练集切点）===')
display(reg_result['sheets']['预测值分桶'])

print('=== 分桶矩阵（三集合合并，含 MAPE + 样本数/占比）===')
display(reg_result['sheets']['分桶矩阵'])

=== 真实值分桶（三集合，训练集切点）===

,数据集,分桶,分箱区间,样本数,样本占比,真实最小值,真实最大值,真实均值,预测均值,预测最低值,预测最高值,误差(预测-真实),MAE,MAPE(%),1值占比
0,训练集,1,"[-inf, -3.0491]",205,0.1002,-8.1610,-3.0517,-4.0368,-3.7992,-5.4386,-2.0001,0.2376,0.4788,11.7006,0.0000
1,训练集,2,"(-3.0491, -2.0945]",204,0.0998,-3.0452,-2.0961,-2.5167,-2.4107,-3.6812,-0.6141,0.1060,0.3480,13.9268,0.0000
2,训练集,3,"(-2.0945, -1.4785]",205,0.1002,-2.0941,-1.4786,-1.7898,-1.7301,-3.3601,-0.2659,0.0597,0.3535,19.9332,0.0000
3,训练集,4,"(-1.4785, -0.9339]",204,0.0998,-1.4782,-0.9351,-1.2105,-1.1434,-2.8466,0.2086,0.0671,0.3899,32.4518,0.0000
4,训练集,5,"(-0.9339, -0.4163]",205,0.1002,-0.9331,-0.4163,-0.6634,-0.6293,-1.9753,0.6792,0.0341,0.3794,59.8067,0.0000
5,训练集,6,"(-0.4163, 0.1649]",204,0.0998,-0.4140,0.1644,-0.1413,-0.1176,-1.2844,1.3105,0.0237,0.3537,733.9955,0.2598
6,训练集,7,"(0.1649, 0.6664]",204,0.0998,0.1656,0.6648,0.4003,0.3107,-1.1029,1.5461,-0.0896,0.3708,105.3525,1.0000
7,训练集,8,"(0.6664, 1.2988]",205,0.1002,0.6668,1.2986,0.9525,0.8738,-0.2814,2.2624,-0.0787,0.3779,41.7741,1.0000
8,训练集,9,"(1.2988, 2.2235]",204,0.0998,1.2997,2.2191,1.7095,1.5760,0.3422,3.7205,-0.1335,0.4164,24.8338,1.0000
9,训练集,10,"(2.2235, +inf]",205,0.1002,2.2264,7.4881,3.1441,2.9170,1.2835,4.2053,-0.2271,0.4683,14.4865,1.0000
10,训练集,All,All,2045,1.0000,-8.1610,7.4881,-0.4154,-0.4154,-5.4386,4.2053,0.0000,0.3937,105.6396,0.4259
11,验证集,1,"[-inf, -3.0491]",58,0.1133,-7.2526,-3.0807,-4.0122,-3.6843,-5.4514,-2.2235,0.3279,0.5557,13.9070,0.0000
12,验证集,2,"(-3.0491, -2.0945]",62,0.1211,-3.0395,-2.1099,-2.5353,-2.3262,-3.4527,-1.0334,0.2091,0.4008,15.7563,0.0000
13,验证集,3,"(-2.0945, -1.4785]",48,0.0938,-2.0706,-1.4794,-1.7864,-1.7749,-2.7555,-0.5673,0.0115,0.3406,19.8084,0.0000
14,验证集,4,"(-1.4785, -0.9339]",63,0.1230,-1.4772,-0.9367,-1.1721,-1.2029,-2.2574,0.0370,-0.0308,0.3844,33.6117,0.0000
15,验证集,5,"(-0.9339, -0.4163]",42,0.0820,-0.9199,-0.4245,-0.6706,-0.5351,-2.0491,1.1080,0.1355,0.5568,89.9013,0.0000
16,验证集,6,"(-0.4163, 0.1649]",59,0.1152,-0.4049,0.1644,-0.1191,-0.1086,-1.2369,1.2127,0.0105,0.3372,588.3619,0.3390
17,验证集,7,"(0.1649, 0.6664]",46,0.0898,0.1697,0.6406,0.3825,0.3004,-0.8394,1.3734,-0.0821,0.4319,140.8657,1.0000
18,验证集,8,"(0.6664, 1.2988]",44,0.0859,0.6696,1.2719,0.9486,0.8162,-0.1955,1.6601,-0.1324,0.3093,33.7517,1.0000
19,验证集,9,"(1.2988, 2.2235]",42,0.0820,1.3136,2.2158,1.7576,1.6871,0.2742,3.1728,-0.0705,0.4470,26.0230,1.0000
20,验证集,10,"(2.2235, +inf]",48,0.0938,2.2257,6.3529,3.3037,3.0453,1.2639,4.1762,-0.2584,0.4521,13.3886,1.0000
21,验证集,All,All,512,1.0000,-7.2526,6.3529,-0.5722,-0.5488,-5.4514,4.1762,0.0234,0.4197,103.5968,0.3906
22,OOT,1,"[-inf, -3.0491]",36,0.0813,-6.5133,-3.0686,-3.8739,-3.5953,-5.2661,-1.9790,0.2786,0.4346,11.6131,0.0000
23,OOT,2,"(-3.0491, -2.0945]",48,0.1084,-3.0053,-2.0988,-2.5361,-2.3621,-3.9434,-0.9814,0.1740,0.4247,16.5859,0.0000
24,OOT,3,"(-2.0945, -1.4785]",41,0.0926,-2.0861,-1.4845,-1.7869,-1.6542,-2.5644,0.1090,0.1327,0.3658,20.9679,0.0000
25,OOT,4,"(-1.4785, -0.9339]",44,0.0993,-1.4759,-0.9436,-1.1961,-1.1071,-2.6129,0.1714,0.0890,0.4021,33.9659,0.0000
26,OOT,5,"(-0.9339, -0.4163]",43,0.0971,-0.9329,-0.4190,-0.6581,-0.5910,-1.8881,0.4723,0.0671,0.3918,62.7633,0.0000
27,OOT,6,"(-0.4163, 0.1649]",57,0.1287,-0.3879,0.1642,-0.1183,-0.0788,-1.3058,1.1889,0.0395,0.3976,444.2274,0.3333
28,OOT,7,"(0.1649, 0.6664]",33,0.0745,0.1791,0.6561,0.3583,0.3816,-0.5956,1.3435,0.0233,0.3902,127.4310,1.0000
29,OOT,8,"(0.6664, 1.2988]",53,0.1196,0.6733,1.2916,0.9935,0.7211,-0.2478,1.7450,-0.2724,0.4376,46.4702,1.0000
30,OOT,9,"(1.2988, 2.2235]",39,0.0880,1.3032,2.1406,1.6615,1.5379,0.2111,2.7935,-0.1236,0.4093,25.5654,1.0000
31,OOT,10,"(2.2235, +inf]",49,0.1106,2.2244,7.6360,3.3824,3.0089,1.4661,4.1374,-0.3735,0.5379,15.1640,1.0000
32,OOT,All,All,443,1.0000,-6.5133,7.6360,-0.2869,-0.2958,-5.2661,4.1374,-0.0089,0.4213,90.2853,0.4357

=== 预测值分桶（三集合，训练集切点）===

,数据集,分桶,分箱区间,样本数,样本占比,真实最小值,真实最大值,真实均值,预测均值,预测最低值,预测最高值,误差(预测-真实),MAE,MAPE(%),1值占比
0,训练集,1,"[-inf, -2.9951]",205,0.1002,-8.1610,-1.8166,-3.9401,-3.8920,-5.4386,-2.9970,0.0481,0.4646,12.1695,0.0000
1,训练集,2,"(-2.9951, -2.0683]",204,0.0998,-4.2511,-1.2865,-2.4810,-2.4676,-2.9923,-2.0698,0.0134,0.3597,15.7779,0.0000
2,训练集,3,"(-2.0683, -1.4525]",205,0.1002,-3.2435,-0.6268,-1.7244,-1.7480,-2.0679,-1.4526,-0.0236,0.3468,24.3849,0.0000
3,训练集,4,"(-1.4525, -0.9014]",204,0.0998,-2.8631,0.4174,-1.1943,-1.1870,-1.4522,-0.9022,0.0073,0.3670,62.8267,0.0049
4,训练集,5,"(-0.9014, -0.3809]",205,0.1002,-2.1524,0.6375,-0.6444,-0.6257,-0.9008,-0.3809,0.0187,0.3629,336.2993,0.0829
5,训练集,6,"(-0.3809, 0.0988]",204,0.0998,-1.5386,1.1046,-0.1181,-0.1378,-0.3766,0.0984,-0.0197,0.4138,142.6120,0.4412
6,训练集,7,"(0.0988, 0.5925]",204,0.0998,-1.1265,1.4136,0.3522,0.3438,0.0992,0.5903,-0.0084,0.3823,273.9653,0.7794
7,训练集,8,"(0.5925, 1.2345]",205,0.1002,-0.9322,2.1824,0.9176,0.9222,0.5930,1.2338,0.0046,0.3973,135.0389,0.9512
8,训练集,9,"(1.2345, 2.182]",204,0.0998,0.0678,3.3518,1.6265,1.6391,1.2372,2.1795,0.0126,0.3827,37.7235,1.0000
9,训练集,10,"(2.182, +inf]",205,0.1002,1.1418,7.4881,3.0537,3.0000,2.1837,4.2053,-0.0537,0.4599,15.6214,1.0000
10,训练集,All,All,2045,1.0000,-8.1610,7.4881,-0.4154,-0.4154,-5.4386,4.2053,0.0000,0.3937,105.6396,0.4259
11,验证集,1,"[-inf, -2.9951]",47,0.0918,-7.2526,-2.7269,-4.1072,-3.9760,-5.4514,-3.0337,0.1312,0.5016,12.1286,0.0000
12,验证集,2,"(-2.9951, -2.0683]",69,0.1348,-4.0501,-1.1033,-2.5951,-2.4935,-2.9838,-2.0757,0.1016,0.4472,18.6130,0.0000
13,验证集,3,"(-2.0683, -1.4525]",68,0.1328,-2.9714,-0.6472,-1.6878,-1.7437,-2.0592,-1.4705,-0.0559,0.4014,30.9150,0.0000
14,验证集,4,"(-1.4525, -0.9014]",45,0.0879,-2.1306,-0.1750,-1.1290,-1.1833,-1.4496,-0.9070,-0.0543,0.3379,53.4005,0.0000
15,验证集,5,"(-0.9014, -0.3809]",44,0.0859,-1.7147,0.6108,-0.5872,-0.6167,-0.8976,-0.3871,-0.0295,0.4893,263.0453,0.1818
16,验证集,6,"(-0.3809, 0.0988]",52,0.1016,-1.2624,1.1056,-0.1546,-0.1074,-0.3741,0.0859,0.0472,0.3896,102.3020,0.4231
17,验证集,7,"(0.0988, 0.5925]",46,0.0898,-0.6772,1.4573,0.2772,0.3103,0.1049,0.5881,0.0331,0.3568,212.9401,0.7174
18,验证集,8,"(0.5925, 1.2345]",49,0.0957,-0.6156,2.1624,0.7803,0.9002,0.6404,1.2127,0.1199,0.4328,367.0785,0.9184
19,验证集,9,"(1.2345, 2.182]",42,0.0820,0.4868,3.0802,1.6917,1.6472,1.2373,2.1223,-0.0445,0.3809,28.5933,1.0000
20,验证集,10,"(2.182, +inf]",50,0.0977,1.4566,6.3529,3.1313,3.0978,2.2111,4.1762,-0.0335,0.4508,16.1053,1.0000
21,验证集,All,All,512,1.0000,-7.2526,6.3529,-0.5722,-0.5488,-5.4514,4.1762,0.0234,0.4197,103.5968,0.3906
22,OOT,1,"[-inf, -2.9951]",35,0.0790,-6.5133,-2.5382,-3.8021,-3.8118,-5.2661,-3.0204,-0.0097,0.3616,9.8892,0.0000
23,OOT,2,"(-2.9951, -2.0683]",42,0.0948,-3.6680,-1.3494,-2.4705,-2.4217,-2.9275,-2.0794,0.0488,0.3951,17.1550,0.0000
24,OOT,3,"(-2.0683, -1.4525]",49,0.1106,-3.2148,-0.8173,-1.8632,-1.7862,-2.0653,-1.4687,0.0770,0.3729,21.8766,0.0000
25,OOT,4,"(-1.4525, -0.9014]",39,0.0880,-2.7568,0.0359,-1.1581,-1.1592,-1.4503,-0.9028,-0.0011,0.4581,163.4528,0.0256
26,OOT,5,"(-0.9014, -0.3809]",44,0.0993,-1.7403,0.3364,-0.6535,-0.6262,-0.8937,-0.3972,0.0273,0.3936,230.9765,0.1136
27,OOT,6,"(-0.3809, 0.0988]",49,0.1106,-1.1091,1.2216,-0.1030,-0.1569,-0.3775,0.0855,-0.0539,0.3805,107.9310,0.4490
28,OOT,7,"(0.0988, 0.5925]",52,0.1174,-1.7397,1.4629,0.3538,0.3401,0.1090,0.5848,-0.0137,0.4738,130.1162,0.7115
29,OOT,8,"(0.5925, 1.2345]",43,0.0971,-0.2540,1.7977,0.8269,0.8830,0.6263,1.2191,0.0561,0.4422,159.3241,0.8837
30,OOT,9,"(1.2345, 2.182]",44,0.0993,0.2826,2.8854,1.6414,1.6063,1.2423,2.1472,-0.0351,0.3799,37.1820,1.0000
31,OOT,10,"(2.182, +inf]",46,0.1038,1.3101,7.6360,3.3436,3.1684,2.2327,4.1374,-0.1752,0.5412,16.9254,1.0000
32,OOT,All,All,443,1.0000,-6.5133,7.6360,-0.2869,-0.2958,-5.2661,4.1374,-0.0089,0.4213,90.2853,0.4357

=== 分桶矩阵（三集合合并，含 MAPE + 样本数/占比）===

,真实值区间\预测值区间,"[-inf, -2.9951]","(-2.9951, -2.0683]","(-2.0683, -1.4525]","(-1.4525, -0.9014]","(-0.9014, -0.3809]","(-0.3809, 0.0988]","(0.0988, 0.5925]","(0.5925, 1.2345]","(1.2345, 2.182]","(2.182, +inf]",合计
0,── 训练集 — MAPE矩阵（行=真实值桶，列=预测值桶） ──,,,,,,,,,,,
1,"[-inf, -3.0491]",10.3,18.39,38.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.7
2,"(-3.0491, -2.0945]",17.44,9.18,19.88,42.14,71.47,NaN,NaN,NaN,NaN,NaN,13.93
3,"(-2.0945, -1.4785]",66.63,25.53,10.55,24.84,53.01,82.72,NaN,NaN,NaN,NaN,19.93
4,"(-1.4785, -0.9339]",NaN,69.87,35.71,14.08,41.04,81.14,118.51,NaN,NaN,NaN,32.45
...,...,...,...,...,...,...,...,...,...,...,...,...
150,"(0.1649, 0.6664]",NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,1.0
151,"(0.6664, 1.2988]",NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0
152,"(1.2988, 2.2235]",NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0
153,"(2.2235, +inf]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
154,合计,0.0,0.0,0.0,0.0256,0.1136,0.449,0.7115,0.8837,1.0,1.0,0.4357

In [10]:
# 自定义切点分桶
custom_bins      = [-3, -1, 0, 1, 3]
custom_bins_pred = [-3, -1, 0, 1, 3]

reg_result_custom = reporter.regression_report(
    datasets_reg,
    filename='LightGBM_回归评估_自定义分桶',
    bins=custom_bins,
    bins_pred=custom_bins_pred,
)
print('=== 自定义切点 — 真实值分桶 ===')
display(reg_result_custom['sheets']['真实值分桶'])
print('=== 自定义切点 — 预测值分桶 ===')
display(reg_result_custom['sheets']['预测值分桶'])
print('=== 自定义切点 — 分桶矩阵 ===')
display(reg_result_custom['sheets']['分桶矩阵'])

=== 自定义切点 — 真实值分桶 ===

,数据集,分桶,分箱区间,样本数,样本占比,真实最小值,真实最大值,真实均值,预测均值,预测最低值,预测最高值,误差(预测-真实),MAE,MAPE(%)
0,训练集,1,"[-inf, -3]",211,0.1032,-8.1610,-3.0009,-4.0079,-3.7731,-5.4386,-2.0001,0.2348,0.4766,11.7466
1,训练集,2,"(-3, -1]",581,0.2841,-2.9992,-1.0048,-1.8659,-1.7897,-3.6812,0.2086,0.0762,0.3641,21.5606
2,训练集,3,"(-1, 0]",382,0.1868,-0.9996,-0.0017,-0.5087,-0.4758,-1.9753,0.9750,0.0329,0.3707,230.8947
3,训练集,4,"(0, 1]",381,0.1863,0.0017,0.9995,0.4945,0.4281,-1.1029,1.9153,-0.0664,0.3731,268.5155
4,训练集,5,"(1, 3]",403,0.1971,1.0016,2.9966,1.8564,1.7581,0.0162,4.0538,-0.0983,0.3919,23.0386
5,训练集,6,"(3, +inf]",87,0.0425,3.0899,7.4881,3.8867,3.4088,1.2835,4.2053,-0.4779,0.5904,14.2193
6,训练集,All,All,2045,1.0000,-8.1610,7.4881,-0.4154,-0.4154,-5.4386,4.2053,0.0000,0.3937,105.6396
7,验证集,1,"[-inf, -3]",61,0.1191,-7.2526,-3.0081,-3.9637,-3.6580,-5.4514,-2.2235,0.3057,0.5404,13.6211
8,验证集,2,"(-3, -1]",158,0.3086,-2.9737,-1.0059,-1.8736,-1.7968,-3.4527,0.0370,0.0768,0.3813,22.5625
9,验证集,3,"(-1, 0]",93,0.1816,-0.9991,-0.0058,-0.5215,-0.4716,-2.0491,1.1080,0.0499,0.4518,184.7318
10,验证集,4,"(0, 1]",92,0.1797,0.0079,0.9588,0.4406,0.3904,-0.8394,1.6601,-0.0502,0.3603,317.4007
11,验证集,5,"(1, 3]",78,0.1523,1.0092,2.9371,1.8035,1.6911,-0.1955,3.8916,-0.1124,0.4151,24.4883
12,验证集,6,"(3, +inf]",30,0.0586,3.0061,6.3529,3.7386,3.4020,1.8332,4.1762,-0.3366,0.4708,11.8263
13,验证集,All,All,512,1.0000,-7.2526,6.3529,-0.5722,-0.5488,-5.4514,4.1762,0.0234,0.4197,103.5968
14,OOT,1,"[-inf, -3]",37,0.0835,-6.5133,-3.0053,-3.8505,-3.5694,-5.2661,-1.9790,0.2811,0.4328,11.6289
15,OOT,2,"(-3, -1]",127,0.2867,-2.9675,-1.0020,-1.8883,-1.7633,-3.9434,0.1090,0.1250,0.3973,22.8551
16,OOT,3,"(-1, 0]",86,0.1941,-0.9921,-0.0215,-0.4834,-0.3848,-1.8881,1.1113,0.0986,0.4084,177.9450
17,OOT,4,"(0, 1]",79,0.1783,0.0187,0.9853,0.4565,0.3755,-1.2688,1.7226,-0.0810,0.3917,235.1902
18,OOT,5,"(1, 3]",88,0.1986,1.0109,2.9960,1.7454,1.5569,-0.0094,3.5715,-0.1885,0.4256,27.5321
19,OOT,6,"(3, +inf]",26,0.0587,3.0415,7.6360,4.1186,3.5159,2.5441,4.1374,-0.6027,0.6395,13.7458
20,OOT,All,All,443,1.0000,-6.5133,7.6360,-0.2869,-0.2958,-5.2661,4.1374,-0.0089,0.4213,90.2853

=== 自定义切点 — 预测值分桶 ===

,数据集,分桶,分箱区间,样本数,样本占比,真实最小值,真实最大值,真实均值,预测均值,预测最低值,预测最高值,误差(预测-真实),MAE,MAPE(%)
0,训练集,1,"[-inf, -3]",202,0.0988,-8.1610,-1.8166,-3.9489,-3.9053,-5.4386,-3.0106,0.0436,0.4663,12.1986
1,训练集,2,"(-3, -1]",571,0.2792,-4.2511,0.4174,-1.8744,-1.8739,-2.9984,-1.0038,0.0005,0.3587,28.5933
2,训练集,3,"(-1, 0]",410,0.2005,-2.1524,0.9906,-0.4978,-0.4919,-0.9971,-0.0016,0.0059,0.3820,239.9911
3,训练集,4,"(0, 1]",377,0.1844,-1.2935,2.1824,0.4740,0.4668,0.0024,0.9971,-0.0072,0.4020,219.1195
4,训练集,5,"(1, 3]",402,0.1966,0.0595,3.7087,1.8239,1.8362,1.0044,2.9987,0.0123,0.3635,36.9347
5,训练集,6,"(3, +inf]",83,0.0406,2.1431,7.4881,3.7439,3.5758,3.0026,4.2053,-0.1681,0.6242,16.7473
6,训练集,All,All,2045,1.0000,-8.1610,7.4881,-0.4154,-0.4154,-5.4386,4.2053,0.0000,0.3937,105.6396
7,验证集,1,"[-inf, -3]",47,0.0918,-7.2526,-2.7269,-4.1072,-3.9760,-5.4514,-3.0337,0.1312,0.5016,12.1286
8,验证集,2,"(-3, -1]",173,0.3379,-4.0501,-0.1919,-1.9466,-1.9382,-2.9838,-1.0096,0.0084,0.4055,28.7133
9,验证集,3,"(-1, 0]",90,0.1758,-1.7147,1.1056,-0.4602,-0.4655,-0.9693,-0.0005,-0.0053,0.4303,181.8863
10,验证集,4,"(0, 1]",96,0.1875,-1.0631,1.6018,0.3721,0.4528,0.0097,0.9777,0.0807,0.3692,157.7609
11,验证集,5,"(1, 3]",79,0.1543,-0.4289,3.6213,1.7949,1.8028,1.0031,2.9457,0.0079,0.4230,197.7507
12,验证集,6,"(3, +inf]",27,0.0527,1.9567,6.3529,3.7315,3.5990,3.0528,4.1762,-0.1325,0.5024,13.5929
13,验证集,All,All,512,1.0000,-7.2526,6.3529,-0.5722,-0.5488,-5.4514,4.1762,0.0234,0.4197,103.5968
14,OOT,1,"[-inf, -3]",35,0.0790,-6.5133,-2.5382,-3.8021,-3.8118,-5.2661,-3.0204,-0.0097,0.3616,9.8892
15,OOT,2,"(-3, -1]",123,0.2777,-3.6680,0.0359,-1.8738,-1.8520,-2.9275,-1.0124,0.0218,0.4026,64.7827
16,OOT,3,"(-1, 0]",90,0.2032,-2.3095,1.2216,-0.5021,-0.4710,-0.9979,-0.0094,0.0311,0.3828,165.2947
17,OOT,4,"(0, 1]",93,0.2099,-1.7397,1.7420,0.4751,0.4592,0.0241,0.9956,-0.0159,0.4669,130.5052
18,OOT,5,"(1, 3]",79,0.1783,-0.1125,3.6625,1.7879,1.8395,1.0232,2.9629,0.0516,0.4092,55.3971
19,OOT,6,"(3, +inf]",23,0.0519,2.9597,7.6360,4.1824,3.6759,3.0066,4.1374,-0.5065,0.6193,12.7008
20,OOT,All,All,443,1.0000,-6.5133,7.6360,-0.2869,-0.2958,-5.2661,4.1374,-0.0089,0.4213,90.2853

=== 自定义切点 — 分桶矩阵 ===

,真实值区间\预测值区间,"[-inf, -3]","(-3, -1]","(-1, 0]","(0, 1]","(1, 3]","(3, +inf]",合计
0,── 训练集 — MAPE矩阵（行=真实值桶，列=预测值桶） ──,,,,,,,
1,"[-inf, -3]",10.27,18.24,NaN,NaN,NaN,NaN,11.75
2,"(-3, -1]",23.23,17.22,46.34,110.43,NaN,NaN,21.56
3,"(-1, 0]",NaN,126.28,124.13,696.86,NaN,NaN,230.89
4,"(0, 1]",NaN,364.24,781.65,124.38,148.74,NaN,268.52
...,...,...,...,...,...,...,...,...
75,"(-1, 0]",0.0,0.0316,0.1174,0.0429,0.0023,0.0,0.1941
76,"(0, 1]",0.0,0.0023,0.0406,0.1106,0.0248,0.0,0.1783
77,"(1, 3]",0.0,0.0,0.0023,0.0519,0.14,0.0045,0.1986
78,"(3, +inf]",0.0,0.0,0.0,0.0,0.0113,0.0474,0.0587
79,合计,0.079,0.2777,0.2032,0.2099,0.1783,0.0519,1.0

## 6. 特征分析报告

In [11]:
analysis_path = reporter.feature_analysis_report(
    df=df,
    features=feature_cols,
    target_col='y_reg',
    dataset_col='dataset',
    month_col='month',
    filename='特征分析报告',
)
print('特征分析报告:', analysis_path)
import openpyxl
wb = openpyxl.load_workbook(analysis_path)
print('sheets:', wb.sheetnames)

特征分析报告: ./output/lgbm_reg\01_feature_analysis\特征分析报告.xlsx
sheets: ['整体', 'by_dataset', 'by_month', '特征分箱图']

## 7. 模型保存与加载

训练时传 `save_dir` 自动保存，目录结构如下：

- `01_feature_analysis/` — 特征分析结果
- `02_feature_selection/` — 特征筛选报告
- `03_model_tuning/tuning_log.xlsx` — 调参日志
- `04_model_report/` — 评估报告（Excel + HTML）
- `05_model_deploy/model.pkl` — joblib 格式，含模型对象、入模特征、最优参数

支持两种加载方式：
1. `ModelTrainer.load()` — 通过 ml_tool 加载，保持完整接口
2. `joblib.load()` — 直接加载原生模型对象，适合生产打分

In [12]:
import os, joblib

# 查看各子目录
print('OUTPUT_DIR 子目录:')
for entry in sorted(os.scandir(OUTPUT_DIR), key=lambda e: e.name):
    if entry.is_dir():
        files = [f.name for f in os.scandir(entry.path)]
        print(f'  {entry.name}/', files)

# 方式一：ModelTrainer.load（保持完整接口）
loaded = ModelTrainer.load(OUTPUT_DIR)
pred_via_trainer = loaded.predict(X_oot)
print('\n[方式一] 入模特征:', loaded.selected_features)
print('[方式一] 预测前5个值:', pred_via_trainer[:5].round(4))

# 方式二：joblib 直接加载原生模型，适合生产环境打分
payload  = joblib.load(os.path.join(OUTPUT_DIR, '05_model_deploy', 'model.pkl'))
model    = payload['model']
features = payload['selected_features']
best_p   = payload['best_params']

print('\n[方式二] model_type:', payload['model_type'])
print('[方式二] 入模特征:', features)
print('[方式二] 最优参数（部分）:', {k: best_p[k] for k in list(best_p)[:3]})

# LightGBM Booster 直接调用 predict
pred_direct = model.predict(X_oot[features])
print('[方式二] 预测前5个值:', pred_direct[:5].round(4))

# 验证两种方式结果完全一致
max_diff = float(np.abs(pred_via_trainer - pred_direct).max())
print('两种方式最大偏差:', round(max_diff, 8), '（应为 0）')
assert max_diff == 0.0

OUTPUT_DIR 子目录:
  01_feature_analysis/ ['特征分析报告.xlsx']
  02_feature_selection/ ['特征筛选报告.xlsx']
  03_model_tuning/ ['tuning_log.xlsx']
  04_model_report/ ['LightGBM_回归模型评估报告.html', 'LightGBM_回归模型评估报告.xlsx', 'LightGBM_回归评估_自定义分桶.html', 'LightGBM_回归评估_自定义分桶.xlsx']
  05_model_deploy/ ['model.pkl']

[方式一] 入模特征: ['f1', 'f2', 'f3', 'f4', 'f5']
[方式一] 预测前5个值: [ 0.431  -3.8194 -2.0021 -0.3023 -3.2381]

[方式二] model_type: lgbm_reg
[方式二] 入模特征: ['f1', 'f2', 'f3', 'f4', 'f5']
[方式二] 最优参数（部分）: {'bagging_fraction': 0.7000000000000001, 'feature_fraction': 1.0, 'lambda_l1': 13}
[方式二] 预测前5个值: [ 0.431  -3.8194 -2.0021 -0.3023 -3.2381]
两种方式最大偏差: 0.0 （应为 0）