# XGBoost 二分类 — 完整流程 Demo

本 notebook 演示基于 `ml_tool` 工具包的 XGBoost 二分类完整流程，涵盖以下步骤：

1. 数据生成与数据集划分
2. 特征分析（缺失率、一值率、分位数、PSI、相关性）
3. WOE/IV 分箱
4. 特征筛选并导出报告
5. XGBoost 模型训练（Hyperopt 调参）
6. 自定义超参数搜索空间（可选）
7. 模型评估报告（分箱 Lift、按月 KS/AUC、特征重要性）
8. 特征分析报告
9. 模型保存与加载验证

In [1]:
import os
import pandas as pd
import numpy as np
from ml_tool import FeatureAnalyzer, Binning, FeatureSelector, ModelTrainer, ReportGenerator, split_dataset

np.random.seed(42)
n = 3000
dates = pd.date_range("2024-01-01", periods=n, freq="D").to_series().sample(frac=1, random_state=42).values
df_raw = pd.DataFrame({
    "f1": np.random.randn(n),
    "f2": np.random.rand(n),
    "f3": np.random.randn(n) * 2,
    "f4": np.random.rand(n),
    "f5": np.random.randn(n),
    "y":  np.random.binomial(1, 0.15, n),
    "report_date": dates,
})
df_raw.loc[df_raw.sample(frac=0.05).index, "f2"] = np.nan
df = split_dataset(df_raw, date_col="report_date", oot_date="2024-09-01", train_ratio=0.8)
df["month"] = df["report_date"].dt.to_period("M").astype(str)

# 模拟附加列（在 split_dataset 调用之后添加到 df）
df["score_A"]    = np.random.uniform(300, 700, n)   # 模拟标品A分
df["score_B"]    = np.random.uniform(350, 750, n)   # 模拟标品B分
df["gain_score"] = np.random.uniform(0, 1, n)       # 模拟外部增益分
df["overdue_30"] = np.random.binomial(1, 0.12, n)   # 模拟逾期30天标签
df["overdue_60"] = np.random.binomial(1, 0.08, n)   # 模拟逾期60天标签

print(df.shape, df["dataset"].value_counts().sort_index().to_dict())

OUTPUT_DIR = "./output/xgb_clf"

数据集划分完成（切点: 2024-09-01, train_ratio=0.8）
  train:    195  (6.5%)
  test :     49  (1.6%)
  oot  :   2756  (91.9%)
(3000, 14) {'oot': 2756, 'test': 49, 'train': 195}

## 1. 特征分析

In [2]:
feature_cols = ["f1", "f2", "f3", "f4", "f5"]
analyzer = FeatureAnalyzer(df[feature_cols])

print("=== 缺失率 ==="); display(analyzer.missing_rate())
print("=== 一值率 ==="); display(analyzer.single_value_rate())
print("=== 分位数统计 ==="); display(analyzer.quantile_stats())

base_df    = df[df["dataset"] == "train"][feature_cols]
compare_df = df[df["dataset"] == "oot"][feature_cols]
psi_df = analyzer.psi(base_df, compare_df)
print("=== PSI（train vs OOT）==="); display(psi_df)
print("=== 相关性（|r|>0.3）==="); display(analyzer.correlation(threshold=0.3))

=== 缺失率 ===

  特征名  缺失数   缺失率
0  f1    0  0.00
1  f2  150  0.05
2  f3    0  0.00
3  f4    0  0.00
4  f5    0  0.00

=== 一值率 ===

  特征名      最高频值     一值率
0  f1  0.496714  0.0003
1  f2       NaN  0.0500
2  f3 -0.380482  0.0003
3  f4  0.648747  0.0003
4  f5  1.508311  0.0003

=== 分位数统计 ===

,特征名,样本数,均值,标准差,最小值,1%分位,5%分位,25%分位,中位数,75%分位,95%分位,99%分位,最大值
0,f1,3000.0,0.032001,0.986808,-3.241267,-2.219490,-1.565074,-0.627541,0.024365,0.673591,1.673504,2.364268,3.926238
1,f2,2850.0,0.495351,0.287139,0.000031,0.011646,0.053723,0.248556,0.489715,0.743174,0.949278,0.988635,0.999461
2,f3,3000.0,-0.035827,2.080612,-7.673311,-4.769815,-3.475749,-1.440090,-0.065302,1.397700,3.363288,4.994851,7.058110
3,f4,3000.0,0.499154,0.291073,0.000158,0.008810,0.050133,0.244087,0.490364,0.756368,0.952307,0.990111,0.999673
4,f5,3000.0,0.012466,0.997329,-3.375579,-2.342613,-1.606774,-0.651083,0.015079,0.673944,1.612335,2.384736,3.428910

=== PSI（train vs OOT）===

  特征名     PSI
0  f1  0.0210
1  f2  0.0850
2  f3  0.0372
3  f4  0.0667
4  f5  0.0581

=== 相关性（|r|>0.3）===

Empty DataFrame
Columns: [特征A, 特征B, 相关系数]
Index: []

## 2. WOE/IV 分箱

In [3]:
train_df = df[df["dataset"] == "train"].reset_index(drop=True)
binning = Binning(n_bins=10)
binning.fit(train_df[feature_cols + ["y"]], target="y", cols=feature_cols)
print("=== IV 汇总 ==="); display(binning.get_iv_summary())
print("=== f1 分箱详情 ==="); display(binning.get_iv_details("f1"))

=== IV 汇总 ===

  特征名      IV
0  f4  2.8960
1  f2  2.1123
2  f1  1.6651
3  f3  1.6425
4  f5  0.2932

=== f1 分箱详情 ===

               分箱区间  坏样本数  总样本数  好样本数     坏样本占比     好样本占比      WOE    IV_bin
0    (-inf, -1.217]     4    20    16  0.121212  0.098765   0.2048  0.004597
1  (-1.217, -0.707]     0    19    19  0.000001  0.117284 -11.6724  1.368974
2  (-0.707, -0.406]     5    20    15  0.151515  0.092593   0.4925  0.029019
3  (-0.406, -0.191]     5    19    14  0.151515  0.086420   0.5615  0.036551
4  (-0.191, 0.0282]     3    20    17  0.090909  0.104938  -0.1435  0.002013
5   (0.0282, 0.226]     6    19    13  0.181818  0.080247   0.8179  0.083075
6    (0.226, 0.477]     1    19    18  0.030303  0.111111  -1.2993  0.104994
7    (0.477, 0.818]     4    20    16  0.121212  0.098765   0.2048  0.004597
8    (0.818, 1.213]     3    19    16  0.090909  0.098765  -0.0829  0.000651
9      (1.213, inf]     2    20    18  0.060606  0.111111  -0.6061  0.030611

## 3. 特征筛选

In [4]:
selector = FeatureSelector(iv_threshold=0.001, psi_threshold=0.5, missing_threshold=0.98, corr_threshold=0.97)
selector.fit(df=train_df[feature_cols + ["y"]], target="y", base_df=base_df, compare_df=compare_df)
print("入选特征:", selector.get_selected())
print("剔除特征:", selector.dropped_cols)
display(selector.get_report())

reporter = ReportGenerator(output_dir=OUTPUT_DIR)
analysis = {
    "缺失率": analyzer.missing_rate(),
    "分位数统计": analyzer.quantile_stats(),
    "PSI": psi_df,
    "相关性": analyzer.correlation(threshold=0.0),
    "IV汇总": binning.get_iv_summary(),
}
path = reporter.feature_selection_report(selector.get_report(), analysis_results=analysis)
print("特征筛选报告:", path)

入选特征: ['f1', 'f2', 'f3', 'f4', 'f5']
剔除特征: []

  特征名    缺失率     PSI      IV 是否保留 剔除原因
0  f1  0.000  0.0210  1.6651   保留
1  f2  0.041  0.0850  2.1123   保留
2  f3  0.000  0.0372  1.6425   保留
3  f4  0.000  0.0667  2.8960   保留
4  f5  0.000  0.0581  0.2932   保留

特征筛选报告: ./output/xgb_clf\02_feature_selection\特征筛选报告.xlsx

## 4. 模型训练（XGBoost 分类）

In [5]:
selected = selector.get_selected()
X_train = df[df["dataset"] == "train"][selected]; y_train = df[df["dataset"] == "train"]["y"]
X_test  = df[df["dataset"] == "test"][selected];  y_test  = df[df["dataset"] == "test"]["y"]
X_oot   = df[df["dataset"] == "oot"][selected];   y_oot   = df[df["dataset"] == "oot"]["y"]

# 两轮流程：
#   第1轮 - 固定默认参数单次训练，用于特征筛选
#   第2轮 - 在筛选后特征上做 Hyperopt 超参搜索（n_trials 实际建议 100）
trainer = ModelTrainer(model_type="xgboost", n_trials=20)
trainer.fit(
    X_train, y_train, X_test, y_test, X_oot, y_oot,
    save_dir=OUTPUT_DIR,
)
print("入模特征数:", len(trainer.selected_features))
print("入模特征:", trainer.selected_features)
print("最优参数:", trainer.best_params)

XGB分类 第1轮（固定参数训练）

XGB分类 第2轮:   0%|                                               | 0/20 [00:00<?, ?it/s]

调参日志已保存至: ./output/xgb_clf\03_model_tuning\tuning_log.xlsx
模型已保存至: ./output/xgb_clf\05_model_deploy
入模特征数: 5
入模特征: ['f1', 'f2', 'f3', 'f4', 'f5']
最优参数: {'gamma': 114.0, 'learning_rate': 0.03, 'max_depth': 3, 'min_child_weight': 1000.0, 'reg_alpha': 300.0, 'reg_lambda': 270.0, 'scale_pos_weight': 2.0, 'subsample': 0.6000000000000001, 'base_score': 0.5, 'booster': 'gbtree', 'objective': 'binary:logistic', 'colsample_bytree': 1, 'n_estimators': 1000, 'random_state': 2024, 'tree_method': 'hist', 'early_stopping_rounds': 30, 'eval_metric': 'auc', 'nthread': -1}

In [6]:
print("调参日志（按 loss 升序，前 10 行）:")
display(
    trainer.trials_log[["round", "trial", "loss", "is_best", "train_auc", "test_auc", "oot_auc"]]
    .sort_values("loss").head(10)
)

调参日志（按 loss 升序，前 10 行）:

   round  trial  loss  is_best  train_auc  test_auc  oot_auc
0    第1轮      1  -0.5     True        0.5       0.5      0.5
18   第2轮     18  -0.5     True        0.5       0.5      0.5
17   第2轮     17  -0.5     True        0.5       0.5      0.5
16   第2轮     16  -0.5     True        0.5       0.5      0.5
15   第2轮     15  -0.5     True        0.5       0.5      0.5
14   第2轮     14  -0.5     True        0.5       0.5      0.5
13   第2轮     13  -0.5     True        0.5       0.5      0.5
12   第2轮     12  -0.5     True        0.5       0.5      0.5
11   第2轮     11  -0.5     True        0.5       0.5      0.5
19   第2轮     19  -0.5     True        0.5       0.5      0.5

## 5. 自定义超参数空间（可选）

In [7]:
from hyperopt import hp
import math

odds = float((y_train == 0).sum() / (y_train == 1).sum())

# ── 查看第一轮固定参数 ─────────────────────────────────────────
params1 = trainer.get_default_params(odds=odds)
print("第1轮固定参数:")
for k, v in params1.items():
    print("  {:30s}: {}".format(k, v))

# ── 查看第二轮默认搜索空间 ────────────────────────────────────
space = trainer.get_default_space(odds=odds)
print("\n第2轮搜索空间 key:")
for k, v in space.items():
    print("  {:30s}: {}".format(k, v))

第1轮固定参数:
  base_score                    : 0.5
  booster                       : gbtree
  objective                     : binary:logistic
  eval_metric                   : auc
  n_estimators                  : 500
  learning_rate                 : 0.05
  max_depth                     : 4
  subsample                     : 0.8
  colsample_bytree              : 0.8
  min_child_weight              : 49
  gamma                         : 5
  reg_alpha                     : 10
  reg_lambda                    : 10
  scale_pos_weight              : 4
  early_stopping_rounds         : 30
  nthread                       : -1

第2轮搜索空间 key:
  base_score                    : 0.5
  booster                       : gbtree
  objective                     : binary:logistic
  learning_rate                 : 0 float
1   hyperopt_param
2     Literal{learning_rate}
3     quniform
4       Literal{0.01}
5       Literal{0.3}
6       Literal{0.01}
  gamma                         : 0 float
1   hyperopt_param
2     Literal{gamma}
3     quniform
4       Literal{0}
5       Literal{200}
6       Literal{2}
  max_depth                     : 0 switch
1   hyperopt_param
2     Literal{max_depth}
3     randint
4       Literal{2}
5   Literal{2}
6   Literal{3}
  subsample                     : 0 float
1   hyperopt_param
2     Literal{subsample}
3     quniform
4       Literal{0.5}
5       Literal{1}
6       Literal{0.1}
  colsample_bytree              : 1
  n_estimators                  : 500
  min_child_weight              : 0 float
1   hyperopt_param
2     Literal{min_child_weight}
3     quniform
4       Literal{100}
5       Literal{1000}
6       Literal{50}
  reg_alpha                     : 0 float
1   hyperopt_param
2     Literal{reg_alpha}
3     quniform
4       Literal{0}
5       Literal{300}
6       Literal{10}
  reg_lambda                    : 0 float
1   hyperopt_param
2     Literal{reg_lambda}
3     quniform
4       Literal{0}
5       Literal{300}
6       Literal{10}
  scale_pos_weight              : 0 float
1   hyperopt_param
2     Literal{scale_pos_weight}
3     quniform
4       Literal{2}
5       Literal{6}
6       Literal{1}
  random_state                  : 2024
  tree_method                   : hist
  early_stopping_rounds         : 30
  eval_metric                   : auc
  nthread                       : -1

In [8]:
# 自定义第1轮固定参数
custom_p1 = {
    "max_depth": 3,
    "learning_rate": 0.03,
    "min_child_weight": max(int(odds * 5), 5),
    "gamma": 2,
}

# 自定义第2轮搜索空间
space["learning_rate"]    = hp.quniform("learning_rate", 0.01, 0.1, 0.01)
space["max_depth"]        = hp.choice("max_depth", [2, 3, 4])
space["min_child_weight"] = hp.quniform("min_child_weight", 5, 50, 5)
space["subsample"]        = hp.quniform("subsample", 0.6, 1.0, 0.1)

# 两轮流程：
#   第1轮 - 使用 custom_p1 固定参数单次训练
#   第2轮 - 使用自定义搜索空间做 Hyperopt 超参搜索
trainer_custom = ModelTrainer(model_type="xgboost", n_trials=10)
trainer_custom.fit(
    X_train, y_train, X_test, y_test, X_oot, y_oot,
    custom_params=custom_p1,
    custom_space=space,
)
print("最终 learning_rate:", trainer_custom.best_params.get("learning_rate"))
print("最终 max_depth:    ", trainer_custom.best_params.get("max_depth"))
print("最终 subsample:    ", trainer_custom.best_params.get("subsample"))

XGB分类 第1轮（固定参数训练）

XGB分类 第2轮:   0%|                                               | 0/10 [00:00<?, ?it/s]

最终 learning_rate: 0.01
最终 max_depth:     4
最终 subsample:     0.6000000000000001

## 6. 模型评估报告

In [9]:
import pandas as pd

# XGBoost 特征重要性从 booster.get_score 取
imp_dict = trainer._trainer.model.get_booster().get_score(importance_type="gain")
fi_df = pd.DataFrame(list(imp_dict.items()), columns=["feature", "importance"])

# 把预测概率列写回 df
df["y_pred_proba"] = float("nan")
df.loc[df["dataset"] == "train", "y_pred_proba"] = trainer.predict_proba(X_train)
df.loc[df["dataset"] == "test",  "y_pred_proba"] = trainer.predict_proba(X_test)
df.loc[df["dataset"] == "oot",   "y_pred_proba"] = trainer.predict_proba(X_oot)

clf_result = reporter.classification_report_from_df(
    df=df,
    target_col="y",
    pred_col="y_pred_proba",
    dataset_col="dataset",
    month_col="month",
    feature_importance=fi_df,
    gain_score_col="gain_score",
    gain_label_col="overdue_30",
    scorecard_cols=["score_A", "score_B"],
    scorecard_label_cols=["overdue_30", "overdue_60"],
    filename="XGBoost_分类评估报告",
)

display(clf_result["summary"])
print("Excel:", clf_result["excel_path"])
print("HTML: ", clf_result["html_path"])

   数据集   KS  AUC   样本量  坏样本数    坏样本率
0  训练集  0.0  0.5   195    33  0.1692
1  验证集  0.0  0.5    49    13  0.2653
2  OOT  0.0  0.5  2756   423  0.1535

Excel: ./output/xgb_clf\04_model_report\XGBoost_分类评估报告.xlsx
HTML:  ./output/xgb_clf\04_model_report\XGBoost_分类评估报告.html

In [10]:
print('=== 分箱分析（训练集 / 验证集 / OOT 合并）===')
display(clf_result['sheets']['分箱分析'])

print('=== 按月KS_AUC ===')
if '按月KS_AUC' in clf_result['sheets']:
    display(clf_result['sheets']['按月KS_AUC'])

print('=== 按月分箱（三集合合并）===')
if '按月分箱' in clf_result['sheets']:
    display(clf_result['sheets']['按月分箱'])

=== 分箱分析（训练集 / 验证集 / OOT 合并）===

Empty DataFrame
Columns: [数据集, 分箱, 分箱区间, 样本数, 样本占比, 坏样本数, 加权样本数, 最低分, 最高分, 坏样本率, Lift, 累计Lift(高→低), 累计Lift(低→高)]
Index: []

=== 按月KS_AUC ===

     数据集    month  样本数  坏样本数    坏样本率   KS  AUC
0    训练集  2024-01   27     6  0.2222  0.0  0.5
1    训练集  2024-02   19     3  0.1579  0.0  0.5
2    训练集  2024-03   25     1  0.0400  0.0  0.5
3    训练集  2024-04   24     3  0.1250  0.0  0.5
4    训练集  2024-05   26     4  0.1538  0.0  0.5
..   ...      ...  ...   ...     ...  ...  ...
101  OOT  2031-11   30     3  0.1000  0.0  0.5
102  OOT  2031-12   31     5  0.1613  0.0  0.5
103  OOT  2032-01   31     5  0.1613  0.0  0.5
104  OOT  2032-02   29     2  0.0690  0.0  0.5
105  OOT  2032-03   18     4  0.2222  0.0  0.5

[106 rows x 7 columns]

=== 按月分箱（三集合合并）===

Empty DataFrame
Columns: [数据集, month, 分箱, 分箱区间, 样本数, 样本占比, 坏样本数, 加权样本数, 最低分, 最高分, 坏样本率, Lift, 累计Lift(高→低), 累计Lift(低→高)]
Index: []

## 7. 特征分析报告

In [11]:
analysis_path = reporter.feature_analysis_report(
    df=df,
    features=feature_cols,
    target_col="y",
    dataset_col="dataset",
    month_col="month",
    filename="特征分析报告",
)
print("特征分析报告:", analysis_path)
import openpyxl
wb = openpyxl.load_workbook(analysis_path)
print("sheets:", wb.sheetnames)

特征分析报告: ./output/xgb_clf\01_feature_analysis\特征分析报告.xlsx
sheets: ['整体', 'by_dataset', 'by_month', '特征分箱图']

## 8. 模型保存与加载

训练时传 `save_dir` 自动保存，各子目录结构如下：

- `01_feature_analysis/` — 特征分析中间结果
- `02_feature_selection/` — 特征筛选报告
- `03_tuning_log/` — 调参日志
- `04_evaluation/` — 模型评估报告（Excel + HTML）
- `05_model_deploy/model.pkl` — joblib 格式，含模型对象、入模特征、最优参数

支持两种加载方式：
1. `ModelTrainer.load()` — 通过 ml_tool 加载，保持完整接口
2. `joblib.load()` — 直接加载原生模型对象，适合生产打分

In [12]:
import os, joblib

# ── 查看各子目录 ──────────────────────────────────────────────
print("OUTPUT_DIR 子目录:")
for name in sorted(os.listdir(OUTPUT_DIR)):
    sub = os.path.join(OUTPUT_DIR, name)
    if os.path.isdir(sub):
        files = os.listdir(sub)
        print(f"  {name}/  -> {files}")
    else:
        print(f"  {name}")

# ── 方式一：ModelTrainer.load（保持完整接口）─────────────────
loaded = ModelTrainer.load(OUTPUT_DIR)
pred_via_trainer = loaded.predict_proba(X_oot)
print("\n[方式一] 入模特征:", loaded.selected_features)
print("[方式一] 预测前5个得分:", pred_via_trainer[:5].round(4))

# ── 方式二：joblib 直接加载原生模型，适合生产环境打分 ──────────
payload  = joblib.load(os.path.join(OUTPUT_DIR, "05_model_deploy", "model.pkl"))
model    = payload["model"]              # xgboost.XGBClassifier
features = payload["selected_features"]
best_p   = payload["best_params"]

print("\n[方式二] model_type:", payload["model_type"])
print("[方式二] 入模特征:", features)
print("[方式二] 最优参数（部分）:", {k: best_p[k] for k in list(best_p)[:3]})

# XGBClassifier 调用 predict_proba 取正类概率
pred_direct = model.predict_proba(X_oot[features])[:, 1]
print("[方式二] 预测前5个得分:", pred_direct[:5].round(4))

# 两种方式预测结果完全一致
max_diff = float(np.abs(pred_via_trainer - pred_direct).max())
print(f"\n两种方式最大偏差: {max_diff:.8f}（应为 0）")
assert max_diff == 0.0

OUTPUT_DIR 子目录:
  01_feature_analysis/  -> ['特征分析报告.xlsx']
  02_feature_selection/  -> ['特征筛选报告.xlsx']
  03_model_tuning/  -> ['tuning_log.xlsx']
  04_model_report/  -> ['XGBoost_分类评估报告.html', 'XGBoost_分类评估报告.xlsx']
  05_model_deploy/  -> ['model.pkl']

[方式一] 入模特征: ['f1', 'f2', 'f3', 'f4', 'f5']
[方式一] 预测前5个得分: [0.5 0.5 0.5 0.5 0.5]

[方式二] model_type: xgboost
[方式二] 入模特征: ['f1', 'f2', 'f3', 'f4', 'f5']
[方式二] 最优参数（部分）: {'gamma': 114.0, 'learning_rate': 0.03, 'max_depth': 3}
[方式二] 预测前5个得分: [0.5 0.5 0.5 0.5 0.5]

两种方式最大偏差: 0.00000000（应为 0）